version: '3.7'
volumes:
    database:
services:
    db:
        image: mysql:latest
        container_name: jap-mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=jpa
            - MYSQL_DATABASE=jpa
            - MYSQL_USER=jpa
            - MYSQL_PASSWORD=jpa
    phpMyAdmin:
            image: phpmyadmin/phpmyadmin:latest
            container_name: jpa-phpmyadmin
            environment:
                - PMA_ARBITRARY=1
            links:
                - db
            ports:
                - 8080:80
            volumes:
                - /sessions
    app:
        build: .
        depends_on:
            - "db"
            - "phpMyAdmin"
        container_name: jpa-app
        ports:
            - 9080:9080
            - 9443:9443